apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4vsv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-4vsv@sha256:34e5313f4df12c9beacce0184b774bfe7824d4f037145c0e0ebd57e55ef7705d
        name: my-nodejs
        resources: {}
status: {}
